apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::703671891029:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-tnfWbzKwp62d
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::703671891029:user/pavan
      username: pavan  
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-10T02:06:01Z"
  name: aws-auth
  namespace: kube-system
  uid: c28a3524-5f05-42a1-b05e-eefa3b90b84e
